name: Deploy Angular App to GCP Bucket

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build -- --configuration production

    # ✅ Paso de autenticación correcto
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # ✅ Setup del CLI (después de auth)
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Check active account
      run: gcloud auth list

    # ✅ Subida usando gsutil con credenciales activadas
    - name: Upload to GCS using gsutil (MIME-aware)
      run: |
        gsutil -m rsync -r -a public-read dist/saludo/browser gs://$GCP_BUCKET_NAME
      env:
        GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
